
name: 'certi_dbt'
version: '1.0.0'
config-version: 2


profile: 'default'

analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  
clean-targets:         
  - "target"
  - "dbt_packages"


vars:

  producto: "Aloe Vera"

tests:
  +store_failures: true
  +database: NGARCIA_DB
  +schema: TEST

models:

  my_new_project:
    +database: NGARCIA_DB

    stg:
      materialized: view
      +tags: Silver
      +schema: SILVER

    marts:
      materialized: table
      +tags: Gold
      +schema: GOLD

on-run-start: 
    - "drop stage if exists ngarcia_db.test.melon" 
    - "create stage ngarcia_db.test.melon" 